repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--skip-string-normalization]
