name: Unit tests and lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: pip install -e .[dev]
    - name: Running pylint
      run: pylint target_hdfs
    - name: Running black check
      run: black --check --diff --skip-string-normalization .
    - name: Running pytest
      run: pytest